[dev-python/mozilla-tokenserver] Add missing dependency
Without the zope-deprecation module the man-page generation will
fail with the following error:

sphinx.errors.ExtensionError: Could not import extension
cornice.ext.sphinxext (exception: No module named deprecation)